"""removed column from the Task table

Revision ID: a330fe9ad377
Revises: 86aca4a6de3a
Create Date: 2021-03-12 02:22:08.802613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a330fe9ad377'
down_revision = '86aca4a6de3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('new', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
